#if !defined(__ctzidn_def_h_)
	#define __ctzidn_def_h_
	
	#define OPENGB_CID_18CID_LENGTH 18
//	#define OPENGB_CID_18CID_LENGTH_1 17
	#define OPENGB_CID_18CID_AREA_LENGTH 6
	#define OPENGB_CID_18CID_BIRTHDAY_LENGTH 8
	#define OPENGB_CID_18CID_ORDER_LENGTH 3
	#define OPENGB_CID_18CID_CHECKSUM_LENGTH 1
	
	#define OPENGB_CID_15CID_LENGTH 15
//	#define OPENGB_CID_15CID_LENGTH_1 14
	#define OPENGB_CID_15CID_AREA_LENGTH 6
	#define OPENGB_CID_15CID_BIRTHDAY_LENGTH 6
	#define OPENGB_CID_15CID_ORDER_LENGTH 3
	#define OPENGB_CID_15CID_CHECKSUM_LENGTH 0
	
typedef unsigned long int	OPENGB_CID_AREA_TYPE;
typedef unsigned long int	OPENGB_CID_BIRTHDAY_TYPE;
typedef unsigned short int	OPENGB_CID_ORDER_TYPE;
typedef unsigned char		OPENGB_CID_CHECKSUM_TYPE;

#endif
